#!/usr/bin/env node

import { readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HARD_MAX = 500;
const SOFT_MAX = 300;

const INCLUDED_EXTENSIONS = new Set([
  ".rs",
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
]);

const EXCLUDED_DIRECTORIES = new Set([
  ".git",
  ".turbo",
  "node_modules",
  "target",
  "dist",
  "build",
  "coverage",
  "tmp",
  "temp",
]);

const EXCLUDED_FILES = new Set([
  "pnpm-lock.yaml",
  "Cargo.lock",
]);

const HARD_EXEMPTIONS = new Map([
  [
    "crates/volt-napi/index.js",
    {
      class: "generated",
      rationale:
        "N-API loader output generated by napi-rs build tooling; manual splitting is not maintainable.",
    },
  ],
]);

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "..", "..");

function isExcludedPath(relativePath) {
  if (EXCLUDED_FILES.has(path.basename(relativePath))) {
    return true;
  }

  const parts = relativePath.split(path.sep);
  for (const part of parts) {
    if (EXCLUDED_DIRECTORIES.has(part)) {
      return true;
    }
  }

  return false;
}

function walkDirectory(rootDir, relativeDir = "") {
  const absoluteDir = path.join(rootDir, relativeDir);
  const entries = readdirSync(absoluteDir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const relativePath = path.join(relativeDir, entry.name);
    if (isExcludedPath(relativePath)) {
      continue;
    }

    const absolutePath = path.join(rootDir, relativePath);

    if (entry.isDirectory()) {
      files.push(...walkDirectory(rootDir, relativePath));
      continue;
    }

    if (!entry.isFile()) {
      continue;
    }

    const extension = path.extname(entry.name);
    if (!INCLUDED_EXTENSIONS.has(extension)) {
      continue;
    }

    files.push({
      absolutePath,
      relativePath: relativePath.replaceAll(path.sep, "/"),
    });
  }

  return files;
}

function countCodeLines(content) {
  const lines = content.split(/\r?\n/u);
  let count = 0;
  for (const line of lines) {
    if (line.trim().length === 0) {
      continue;
    }
    count += 1;
  }
  return count;
}

const files = walkDirectory(repoRoot);
const results = files
  .map((file) => {
    const content = readFileSync(file.absolutePath, "utf8");
    const lines = countCodeLines(content);
    const hardExemption = HARD_EXEMPTIONS.get(file.relativePath) ?? null;
    return {
      file: file.relativePath,
      lines,
      hardExemption,
    };
  })
  .sort((a, b) => b.lines - a.lines);

const hardViolations = results.filter(
  (item) => item.lines > HARD_MAX && !item.hardExemption,
);
const softViolations = results.filter(
  (item) => item.lines > SOFT_MAX && item.lines <= HARD_MAX,
);
const hardExemptionMatches = results.filter(
  (item) => item.lines > HARD_MAX && item.hardExemption,
);
const staleHardExemptions = [...HARD_EXEMPTIONS.keys()].filter(
  (relativePath) =>
    !results.some(
      (result) => result.file === relativePath && result.lines > HARD_MAX,
    ),
);

if (softViolations.length > 0) {
  console.log(`LOC soft warning (> ${SOFT_MAX} lines):`);
  for (const violation of softViolations) {
    console.log(`  - ${violation.file}: ${violation.lines}`);
  }
}

if (hardExemptionMatches.length > 0) {
  console.log("LOC hard-cap exemptions:");
  for (const exempt of hardExemptionMatches) {
    console.log(
      `  - ${exempt.file}: ${exempt.lines} [${exempt.hardExemption.class}] ${exempt.hardExemption.rationale}`,
    );
  }
}

if (staleHardExemptions.length > 0) {
  console.warn("LOC exemption cleanup recommended (entries no longer exceed hard-cap):");
  for (const exemptPath of staleHardExemptions) {
    console.warn(`  - ${exemptPath}`);
  }
}

if (hardViolations.length > 0) {
  console.error(`LOC hard violation (> ${HARD_MAX} lines):`);
  for (const violation of hardViolations) {
    console.error(`  - ${violation.file}: ${violation.lines}`);
  }
  process.exit(1);
}

console.log(
  `LOC guard passed (${results.length} files checked, hard<=${HARD_MAX}, soft<=${SOFT_MAX}).`,
);
