export const DEFAULT_IPC_MAX_PAYLOAD_BYTES = 256 * 1024;
export const DEFAULT_IPC_MAX_IN_FLIGHT_PER_WINDOW = 32;
export const IPC_PAYLOAD_TOO_LARGE_CODE = 'IPC_PAYLOAD_TOO_LARGE';
export const IPC_IN_FLIGHT_LIMIT_CODE = 'IPC_IN_FLIGHT_LIMIT';
export const IPC_INVALID_REQUEST_CODE = 'IPC_HANDLER_ERROR';
