use boa_engine::native_function::NativeFunction;
use boa_engine::object::ObjectInitializer;
use boa_engine::property::Attribute;
use boa_engine::{Context, JsResult, js_string};

use super::{bridge_core, bridge_fs, bridge_grants, bridge_storage};

pub fn register_native_bridge(context: &mut Context) -> JsResult<()> {
    let bridge = ObjectInitializer::new(context)
        .function(
            NativeFunction::from_fn_ptr(bridge_core::manifest),
            js_string!("manifest"),
            0,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_grants::delegated_grants),
            js_string!("delegatedGrants"),
            0,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::send_log),
            js_string!("sendLog"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::register_command),
            js_string!("registerCommand"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::unregister_command),
            js_string!("unregisterCommand"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::subscribe_event),
            js_string!("subscribeEvent"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::unsubscribe_event),
            js_string!("unsubscribeEvent"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::emit_event),
            js_string!("emitEvent"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::register_ipc),
            js_string!("registerIpc"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_core::unregister_ipc),
            js_string!("unregisterIpc"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_read_file),
            js_string!("fsReadFile"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_write_file),
            js_string!("fsWriteFile"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_read_dir),
            js_string!("fsReadDir"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_stat),
            js_string!("fsStat"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_exists),
            js_string!("fsExists"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_mkdir),
            js_string!("fsMkdir"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::fs_remove),
            js_string!("fsRemove"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_read_file),
            js_string!("grantFsReadFile"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_write_file),
            js_string!("grantFsWriteFile"),
            3,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_read_dir),
            js_string!("grantFsReadDir"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_stat),
            js_string!("grantFsStat"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_exists),
            js_string!("grantFsExists"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_mkdir),
            js_string!("grantFsMkdir"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_fs::grant_fs_remove),
            js_string!("grantFsRemove"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_storage::storage_get),
            js_string!("storageGet"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_storage::storage_set),
            js_string!("storageSet"),
            2,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_storage::storage_has),
            js_string!("storageHas"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_storage::storage_delete),
            js_string!("storageDelete"),
            1,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_storage::storage_keys),
            js_string!("storageKeys"),
            0,
        )
        .function(
            NativeFunction::from_fn_ptr(bridge_grants::request_access),
            js_string!("requestAccess"),
            1,
        )
        .build();

    context.register_global_property(
        js_string!("__volt_plugin_native__"),
        bridge,
        Attribute::all(),
    )
}
