/* auto-generated by NAPI-RS */
/* eslint-disable */
/** JavaScript-facing application class. */
export declare class VoltApp {
  /** Create a new VoltApp from a JSON configuration object. */
  constructor(config: any)
  /** Queue a window for creation. The window will be created when `run()` is called. */
  createWindow(config: any): void
  /** Register an event callback. The callback receives a JSON string with event details. */
  onEvent(callback: ((err: Error | null, arg: string) => any)): void
  /**
   * Run the application event loop runtime.
   *
   * On non-macOS platforms this starts a split runtime:
   * - native loop on a dedicated thread
   * - Node bridge callback dispatch on a dedicated thread
   *
   * On macOS, tao/wry main-thread requirements keep the native loop on the
   * current thread.
   */
  run(): void
}

/** JavaScript-facing global shortcut manager. */
export declare class VoltGlobalShortcut {
  /** Create a new global shortcut manager. */
  constructor()
  /**
   * Register a global shortcut with an accelerator string (e.g., "CmdOrCtrl+Shift+P").
   * The callback receives the accelerator string when triggered.
   */
  register(accelerator: string, callback: ((err: Error | null, arg: string) => any)): void
  /** Unregister a previously registered global shortcut. */
  unregister(accelerator: string): void
  /** Unregister all global shortcuts. */
  unregisterAll(): void
  /** Check if a shortcut is registered. */
  isRegistered(accelerator: string): boolean
  /** Get all registered accelerator strings. */
  getRegistered(): Array<string>
}

/** JavaScript-facing IPC handler registry. */
export declare class VoltIpc {
  /** Create a new IPC handler registry. */
  constructor()
  /**
   * Register an IPC handler. The callback receives JSON args string and should
   * return a JSON result string.
   */
  handle(channel: string, callback: ((err: Error | null, arg: string) => string)): void
  /** Remove a registered IPC handler. */
  removeHandler(channel: string): void
  /** Process a raw IPC message from the WebView. Returns the response JSON string. */
  processMessage(raw: string): string
  /** Register a callback to receive event emission requests (for relaying to WebView). */
  onEmit(callback: ((err: Error | null, arg: string) => any)): void
  /**
   * Emit an event to all registered WebView windows.
   * Returns the JavaScript code to evaluate in the WebView.
   */
  emitEvent(event: string, data: string): string
}

/** JavaScript-facing menu builder. */
export declare class VoltMenu {
  /** Create a new menu from a JSON template array. */
  constructor(template: any)
  /**
   * Build and set this menu as the application menu bar.
   * Must be called from the main thread (event loop context).
   */
  setAsAppMenu(): void
  /** Get the number of top-level menu items. */
  itemCount(): number
}

/** JavaScript-facing system tray class. */
export declare class VoltTray {
  /** Create a new system tray icon from a JSON configuration. */
  constructor(config: any)
  /** Set the tray tooltip text. */
  setTooltip(tooltip: string): void
  /** Set the tray icon from an image file path. */
  setIcon(iconPath: string): void
  /** Set the tray visibility. */
  setVisible(visible: boolean): void
  /** Register a click callback. Receives a JSON string with event details. */
  onClick(callback: ((err: Error | null, arg: string) => any)): void
  /** Destroy the tray icon and clean up resources. */
  destroy(): void
}

/** Read an image from the system clipboard. */
export declare function clipboardReadImage(): VoltImageData

/** Read text from the system clipboard. */
export declare function clipboardReadText(): string

/** Write an image to the system clipboard. */
export declare function clipboardWriteImage(data: VoltImageData): void

/** Write text to the system clipboard. */
export declare function clipboardWriteText(text: string): void

/** Show a message dialog. Returns true if user confirmed, false otherwise. */
export declare function dialogShowMessage(options: any): boolean

/** Show an open file/folder dialog. Returns selected paths, or empty array if cancelled. */
export declare function dialogShowOpen(options: any): Array<string>

/**
 * Show an open folder dialog that creates filesystem scope grants for selected directories.
 * Requires both `dialog` and `fs` permissions.
 * Returns paths and corresponding grant IDs, or empty arrays if cancelled.
 */
export declare function dialogShowOpenWithGrant(options: any): GrantDialogResult

/** Show a save file dialog. Returns the selected path, or null if cancelled. */
export declare function dialogShowSave(options: any): string | null

/** Copy a file within the scope. */
export declare function fsCopy(baseDir: string, from: string, to: string): void

/** Check whether a path exists within the base scope directory. */
export declare function fsExists(baseDir: string, path: string): boolean

/** Create a directory (and parents). Path is relative to the base scope directory. */
export declare function fsMkdir(baseDir: string, path: string): void

/** List entries in a directory. Path is relative to the base scope directory. */
export declare function fsReadDir(baseDir: string, path: string): Array<string>

/** Read a file as raw bytes. Path is relative to the base scope directory. */
export declare function fsReadFile(baseDir: string, path: string): Buffer

/** Read a file as a UTF-8 string. Path is relative to the base scope directory. */
export declare function fsReadFileText(baseDir: string, path: string): string

/** Remove a file or directory. Path is relative to the base scope directory. */
export declare function fsRemove(baseDir: string, path: string): void

/** Rename (move) a file or directory within the scope. */
export declare function fsRename(baseDir: string, from: string, to: string): void

/**
 * Resolve a grant ID to its root path string.
 * Returns the absolute path for the grant, or throws if the grant is invalid.
 */
export declare function fsResolveGrant(grantId: string): string

/** Get file/directory metadata. Path is relative to the base scope directory. */
export declare function fsStat(baseDir: string, path: string): VoltFileInfo

/** Stop a watcher and release resources. */
export declare function fsWatchClose(watcherId: string): void

/** Drain all pending events from a watcher. Returns a JSON-serializable array. */
export declare function fsWatchPoll(watcherId: string): Array<any>

/** Start watching a directory for changes. Returns a watcher ID. */
export declare function fsWatchStart(baseDir: string, subpath: string, recursive: boolean, debounceMs: number): string

/** Write data to a file. Path is relative to the base scope directory. */
export declare function fsWriteFile(baseDir: string, path: string, data: Buffer): void

/** Result from a grant-aware open dialog. */
export interface GrantDialogResult {
  /** Selected file/directory paths. */
  paths: Array<string>
  /** Grant IDs corresponding to each selected path (only for directories). */
  grantIds: Array<string>
}

/**
 * Show a native OS notification.
 * Accepts a JSON object with `title` (required), `body` (optional), and `icon` (optional).
 */
export declare function notificationShow(options: any): void

/**
 * Open a URL in the default system application.
 * Only http, https, and mailto schemes are allowed.
 */
export declare function shellOpenExternal(url: string): void

/** Reveal a file or directory in the platform file manager. */
export declare function shellShowItemInFolder(path: string): void

/** Apply a downloaded update by replacing the current binary. */
export declare function updaterApply(data: Buffer): void

/**
 * Check for available updates.
 * Returns update info if available, or null if up to date.
 */
export declare function updaterCheck(config: any): Promise<any | null>

/**
 * Download an update and verify its SHA-256 checksum and Ed25519 signature.
 * Returns the verified binary data as a Buffer.
 */
export declare function updaterDownloadAndVerify(config: any, info: any): Promise<Buffer>

/** File metadata returned by fs_stat. */
export interface VoltFileInfo {
  /** File size in bytes. */
  size: number
  /** Whether the path is a file. */
  isFile: boolean
  /** Whether the path is a directory. */
  isDir: boolean
  /** Whether the file is read-only. */
  readonly: boolean
  /** Last modification time as milliseconds since Unix epoch. */
  modifiedMs: number
  /** Creation time as milliseconds since Unix epoch, or null if unavailable. */
  createdMs?: number
}

/** Image data returned from clipboard operations. */
export interface VoltImageData {
  /** Raw RGBA pixel data. */
  rgba: Buffer
  /** Image width in pixels. */
  width: number
  /** Image height in pixels. */
  height: number
}

/** Close a window by its JS ID. */
export declare function windowClose(jsId: string): void

/** Get the number of tracked windows. */
export declare function windowCount(): number

/** Execute a JavaScript string in a window's webview. */
export declare function windowEvalScript(jsId: string, script: string): void

/** Focus a window by its JS ID. */
export declare function windowFocus(jsId: string): void

/** Maximize a window by its JS ID. */
export declare function windowMaximize(jsId: string): void

/** Minimize a window by its JS ID. */
export declare function windowMinimize(jsId: string): void

/** Restore a window by its JS ID. */
export declare function windowRestore(jsId: string): void

/** Show a window by its JS ID. */
export declare function windowShow(jsId: string): void
