/**
 * Ambient type declarations for the @voltkit/volt-native napi module.
 * These types mirror the Rust napi bindings in crates/volt-napi/src/.
 * The actual index.js and index.d.ts are auto-generated by napi-rs at build time.
 */
declare module '@voltkit/volt-native' {
  // ── Clipboard ──────────────────────────────────────────────────────────

  /** Read text from the system clipboard. */
  export function clipboardReadText(): string;

  /** Write text to the system clipboard. */
  export function clipboardWriteText(text: string): void;

  /** Read an image from the system clipboard. */
  export function clipboardReadImage(): NativeImageData;

  /** Write an image to the system clipboard. */
  export function clipboardWriteImage(data: NativeImageData): void;

  /** Image data with RGBA pixels used by clipboard operations. */
  export interface NativeImageData {
    rgba: Buffer;
    width: number;
    height: number;
  }

  // ── Dialog ─────────────────────────────────────────────────────────────

  export interface NativeDialogFileFilter {
    name: string;
    extensions: string[];
  }

  export interface NativeOpenDialogOptions {
    title?: string;
    default_path?: string;
    filters?: NativeDialogFileFilter[];
    multiple?: boolean;
    directory?: boolean;
  }

  export interface NativeSaveDialogOptions {
    title?: string;
    default_path?: string;
    filters?: NativeDialogFileFilter[];
  }

  export interface NativeMessageDialogOptions {
    dialog_type?: 'info' | 'warning' | 'error';
    title?: string;
    message: string;
    buttons?: string[];
  }

  /** Show an open file/folder dialog. Returns selected paths. */
  export function dialogShowOpen(options: NativeOpenDialogOptions): string[];

  /** Show a save file dialog. Returns path or null if cancelled. */
  export function dialogShowSave(options: NativeSaveDialogOptions): string | null;

  /** Show a message dialog. Returns true if user confirmed. */
  export function dialogShowMessage(options: NativeMessageDialogOptions): boolean;

  // ── File System ────────────────────────────────────────────────────────

  /** Read a file as raw bytes. */
  export function fsReadFile(baseDir: string, path: string): Buffer;

  /** Read a file as a UTF-8 string. */
  export function fsReadFileText(baseDir: string, path: string): string;

  /** Write data to a file. */
  export function fsWriteFile(baseDir: string, path: string, data: Buffer): void;

  /** List entries in a directory. */
  export function fsReadDir(baseDir: string, path: string): string[];

  /** Get file metadata. */
  export function fsStat(baseDir: string, path: string): NativeFileInfo;

  /** Create a directory and parents. */
  export function fsMkdir(baseDir: string, path: string): void;

  /** Remove a file or directory. */
  export function fsRemove(baseDir: string, path: string): void;

  /** File metadata returned by fsStat. */
  export interface NativeFileInfo {
    size: number;
    isFile: boolean;
    isDir: boolean;
    readonly: boolean;
  }

  // ── Shell ──────────────────────────────────────────────────────────────

  /** Open a URL in the default system application. */
  export function shellOpenExternal(url: string): void;

  // ── Notification ───────────────────────────────────────────────────────

  export interface NativeNotificationOptions {
    title: string;
    body?: string;
    icon?: string;
  }

  /** Show a native OS notification. */
  export function notificationShow(options: NativeNotificationOptions): void;

  // ── Global Shortcut ────────────────────────────────────────────────────

  /** Global keyboard shortcut manager. */
  export class VoltGlobalShortcut {
    constructor();
    register(accelerator: string, callback: (accelerator: string) => void): void;
    unregister(accelerator: string): void;
    unregisterAll(): void;
    isRegistered(accelerator: string): boolean;
    getRegistered(): string[];
  }

  // ── Updater ────────────────────────────────────────────────────────────

  /** Check for available updates. Returns update info or null. */
  export interface NativeUpdateConfig {
    endpoint: string;
    public_key: string;
    current_version: string;
  }

  export interface NativeUpdateInfo {
    version: string;
    url: string;
    signature: string;
    sha256: string;
    target: string;
  }

  /** Check for available updates. Returns update info or null. */
  export function updaterCheck(config: NativeUpdateConfig): Promise<NativeUpdateInfo | null>;

  /** Download and verify an update. Returns the verified binary data. */
  export function updaterDownloadAndVerify(
    config: NativeUpdateConfig,
    info: NativeUpdateInfo,
  ): Promise<Buffer>;

  /** Apply a downloaded update by replacing the current binary. */
  export function updaterApply(data: Buffer): void;

  // ── Tray ───────────────────────────────────────────────────────────────

  export interface NativeTrayConfig {
    tooltip?: string;
    icon?: string;
  }

  /** System tray icon manager. */
  export class VoltTray {
    constructor(config: NativeTrayConfig);
    setTooltip(tooltip: string): void;
    setIcon(iconPath: string): void;
    setVisible(visible: boolean): void;
    onClick(callback: (err: Error | null, event: string) => void): void;
    destroy(): void;
  }

  // ── Menu ───────────────────────────────────────────────────────────────

  /** Native application menu builder. */
  export class VoltMenu {
    constructor(template: unknown[]);
    setAsAppMenu(): void;
    itemCount(): number;
  }

  // ── Window ──────────────────────────────────────────────────────────────

  /** Close a window by its JS ID. */
  export function windowClose(jsId: string): void;

  /** Show a window by its JS ID. */
  export function windowShow(jsId: string): void;

  /** Focus a window by its JS ID. */
  export function windowFocus(jsId: string): void;

  /** Maximize a window by its JS ID. */
  export function windowMaximize(jsId: string): void;

  /** Minimize a window by its JS ID. */
  export function windowMinimize(jsId: string): void;

  /** Restore a window by its JS ID. */
  export function windowRestore(jsId: string): void;

  /** Execute a script in a window's webview by its JS ID. */
  export function windowEvalScript(jsId: string, script: string): void;

  /** Get the number of registered native windows. */
  export function windowCount(): number;

  // ── App ────────────────────────────────────────────────────────────────

  export interface NativeAppConfig {
    name?: string;
    devtools?: boolean;
    permissions?: string[];
  }

  export interface NativeWindowCreateConfig {
    jsId?: string;
    url?: string;
    html?: string;
    devtools?: boolean;
    transparent?: boolean;
    userAgent?: string;
    allowedOrigins?: string[];
    initScript?: string;
    window?: {
      title?: string;
      width?: number;
      height?: number;
      minWidth?: number;
      minHeight?: number;
      maxWidth?: number;
      maxHeight?: number;
      resizable?: boolean;
      decorations?: boolean;
      transparent?: boolean;
      alwaysOnTop?: boolean;
      maximized?: boolean;
      visible?: boolean;
      x?: number;
      y?: number;
    };
  }

  /** Native application wrapper. */
  export class VoltApp {
    constructor(config: NativeAppConfig);
    createWindow(config: NativeWindowCreateConfig): void;
    onEvent(callback: (event: string) => void): void;
    run(): void;
  }

  // ── IPC ────────────────────────────────────────────────────────────────

  /** IPC handler registry. */
  export class VoltIpc {
    constructor();
    handle(channel: string, callback: (args: string) => string): void;
    removeHandler(channel: string): void;
    processMessage(raw: string): string;
    onEmit(callback: (event: string) => void): void;
    emitEvent(event: string, data: string): void;
  }
}
